criaçao do header do horarios
Guardians-DSC/horarios-ufcg pull request #137
Opened 2020-09-21 01:57 UTC by carolvalenca

2020-09-22 02:38 UTC, ArthurFerrao commented
Ficou muito bom, só tem uma coisa que gostaria que tu desse uma olhada.

2020-09-22 02:46 UTC, ArthurFerrao requested changes

2020-09-22 02:46 UTC, ArthurFerrao commented on horarios-react/src/components/Header/style.css
> +    right: 22rem;
O ícone da lupa está saindo quando diminui bastante a tela, como na imagem abaixo. 
![image](https://user-images.githubusercontent.com/15989443/93839103-38e8d900-fc62-11ea-862f-a37c12eb03b6.png)
Acho que isso acontece por causa desse right, como não tem nenhuma tag pai com "position" ele ta sendo posicionado relativo a página.
Talvez adicionar um "position: relative" na div search-bar e mudar esse right pra left já resolva isso.

2020-09-23 23:17 UTC, RaylaMedeiros requested changes

2020-09-23 23:17 UTC, RaylaMedeiros commented on horarios-react/src/components/Header/index.js
> +            <div className='header-content'>
Talvez essas duas divs pudessem ser a mesma coisa, já que o container só tem 1 filho

2020-09-23 23:17 UTC, RaylaMedeiros commented on horarios-react/src/components/Header/style.css
> +    grid-template-columns: repeat(3, 1fr);
Poderia usar um flex aqui, e separar os itens com um `justify-content: space-between`

2020-09-28 20:07 UTC, carolvalenca commented on horarios-react/src/components/Header/style.css
> +    grid-template-columns: repeat(3, 1fr);
mulher eu tentei mas como as divs dos cantos nao tem a mesma largura o nome no meio não ficou centralizado certinho, daí apelei pra grid mesmo

2020-09-28 22:14 UTC, ArthurFerrao approved these changes

2020-09-29 14:33 UTC, RaylaMedeiros approved these changes

2020-09-29 16:15 UTC, merged