componentes de dia, hora e tabela
Guardians-DSC/horarios-ufcg pull request #140
Opened 2020-10-11 07:03 UTC by carolvalenca

2020-10-11 20:24 UTC, RaylaMedeiros requested changes
Tudo funciona bem, mas acredito que alguns ajustes precisam ser feitos para que o código fique mais legível e fácil de manter

2020-10-11 20:24 UTC, RaylaMedeiros commented on horarios-react/src/assets/arrow-down.svg
> +</g>
Essas tags são desnecessárias

2020-10-11 20:24 UTC, RaylaMedeiros commented on horarios-react/src/assets/arrow-down.svg
> +<g>
Aqui também, pode deixar só o path

2020-10-11 20:24 UTC, RaylaMedeiros commented on horarios-react/src/assets/arrow-down.svg
> +<svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
Exporta como um componente, ai esse `<?xml>, <!DOCTYPE>` e as props `xmlns:xlink, x, y` não são mais necessários

2020-10-11 20:24 UTC, RaylaMedeiros commented on horarios-react/src/assets/arrow-up.svg
> +<?xml version="1.0" encoding="iso-8859-1"?>
Não são necessários 2 ícones, você pode adicionar um `transform` e rotacionar a seta

2020-10-11 20:24 UTC, RaylaMedeiros commented on horarios-react/src/components/Table/index.js
> +                <Day content="SEG"/>
Tenta uniformizar o uso das aspas, pra ficar apenas um tipo de aspas

2020-10-11 20:24 UTC, RaylaMedeiros commented on horarios-react/src/components/Table/index.js
> +                <Hour content="22h" color="gray"/>
Aqui pode ser usado um map

2020-10-11 20:24 UTC, RaylaMedeiros commented on horarios-react/src/components/Table/style.css
> +    justify-content: flex-end;
por que um flex e não um grid?

2020-10-11 22:31 UTC, ArthurFerrao commented on horarios-react/src/components/Table/style.css
> +    justify-content: flex-end;
Também acho que um grid seria melhor aqui e resolveria o problema que todos os dias estão ficando no final. 
![image](https://user-images.githubusercontent.com/15989443/95691752-e020b680-0bf7-11eb-9e7e-f18e17fa9b0d.png)

2020-10-16 22:21 UTC, ArthurFerrao requested changes
Ficou muito bom, só da uma olhada nesses pontos que comentei que ta aprovado.

2020-10-16 22:21 UTC, ArthurFerrao commented on horarios-react/src/components/Table/index.js
> +                    <Hour content={elem.hour} color={elem.color}/>
Acho que seria bom que essa cor fosse gerada automaticamente, já que as horas não são fixas(elas vem da api) e assim as linhas vão variar dependendo da api.

2020-10-16 22:21 UTC, ArthurFerrao commented on horarios-react/src/components/Table/style.css
> +}
Para resolver o problema que falei acho que a solução usada na implementação em vue funciona aqui também. Algo assim deve resolver:
```
.hours #hour-container:nth-child(even) {
    background-color: #eee;
}
```

2020-10-16 22:34 UTC, ArthurFerrao commented on horarios-react/src/components/Table/index.js
> +                {daysArray.map(elem => (
Nesses maps usa uma função que recebe um index e passa pro teu componente como uma key, assim:
`array.map((elem, index) => <TeuComponente key={index} />)`
Que resolve um erro que da no console por causa disso.

2020-10-16 23:02 UTC, RaylaMedeiros commented on horarios-react/src/components/Table/index.js
> +                {daysArray.map(elem => (
Precisa ser assim não, pode passar algum atributo do elem na key, tipo `array.map(elem => <TeuComponente key={elem.day} />`

2020-10-16 23:03 UTC, RaylaMedeiros commented on horarios-react/src/components/Table/index.js
> +                <span></span>
Não entendi o span vazio

2020-10-16 23:27 UTC, RaylaMedeiros commented on horarios-react/src/components/Hour/index.js
> +          <div className="content">
Tenta deixar tudo com aspas simples ou com aspas duplas

2020-10-16 23:27 UTC, RaylaMedeiros commented on horarios-react/src/components/Table/index.js
> +            <div className="days">
O mesmo aqui(sobre as aspas)

2020-10-16 23:29 UTC, RaylaMedeiros commented on horarios-react/src/components/Table/style.css
> +    /* justify-content: flex-end; */
Acho que esse comentário pode ser removido

2020-10-16 23:42 UTC, RaylaMedeiros commented on horarios-react/src/components/Hour/index.js
> +            <p>{content}</p>
coloca um padding-left aqui ou aumenta o padding-left no hour-container, pra desgrudar da lateral da tela

2020-10-18 04:43 UTC, ArthurFerrao requested changes

2020-10-18 04:43 UTC, ArthurFerrao commented on horarios-react/src/components/Table/style.css
> +#table-container .hours #hour-container:nth-child(even) {
No lugar do even tenta usar o odd pra ele poder começar com a faixa cinza.

2020-10-18 04:43 UTC, ArthurFerrao commented on horarios-react/src/components/Hour/style.css
> +#hour-container .hour {
Acho que seria bom só um espaço entre a hora e o arrow.

2020-10-18 15:55 UTC, ArthurFerrao approved these changes

2020-10-23 01:00 UTC, RaylaMedeiros approved these changes

2020-10-23 03:49 UTC, merged