botao de limpar filtro
Guardians-DSC/horarios-ufcg pull request #141
Opened 2020-10-15 03:28 UTC by carolvalenca

2020-10-15 05:48 UTC, ArthurFerrao requested changes

2020-10-15 05:48 UTC, ArthurFerrao commented on horarios-react/src/components/FilterButton/index.js
> +       <button id='filter-button-container' className={color} onClick={() => click(content)}>
Acho que é mais simples passar o "active" e no className adicionar uma condição assim `active ? "active-color" : "normal-color"`.  Assim você pode tirar todas aquelas atribuições de color do componente pai.

2020-10-15 05:48 UTC, ArthurFerrao commented on horarios-react/src/components/Filter/index.js
> +                }
Tirando esse atributo "color" esse if e else pode ser simplificado com um `newArray[obj].active = !newArray[obj].active`

2020-10-18 16:53 UTC, ArthurFerrao requested changes

2020-10-18 16:53 UTC, ArthurFerrao commented on horarios-react/src/components/Filter/index.js
> +    }
Acho que assim ele funciona sem precisar usar esse Render: 
```
    function click(buttonContent) {
        setButtonsInfo(buttonsInfo.map(item => {
            if(item.label === buttonContent)  item.active = !item.active;
            return item;
        }));
    }
```

2020-10-18 16:53 UTC, ArthurFerrao commented on horarios-react/src/components/Filter/index.js
> +    }
Acho que assim ele funciona sem precisar usar esse Render:
```
    function clear() {
        setButtonsInfo(buttonsInfo.map(item => {
            item.active = false;
            return item;
        }));
    }
```

2020-10-18 16:53 UTC, ArthurFerrao commented on horarios-react/src/components/Filter/index.js
> +        setButtonsInfo([
Acho que tu pode setar esse array direto no useState.

2020-10-20 17:46 UTC, ArthurFerrao approved these changes

2020-10-21 00:33 UTC, RaylaMedeiros commented on horarios-react/src/components/Filter/index.js
> +    async function click(buttonContent) {
Por que usasse `async` aqui?

2020-10-21 00:42 UTC, RaylaMedeiros requested changes

2020-10-21 00:42 UTC, RaylaMedeiros commented on horarios-react/src/components/Filter/index.js
> +    async function click(buttonContent) {
Por que usasse async aqui?

2020-10-21 00:42 UTC, RaylaMedeiros commented on horarios-react/src/components/Filter/index.js
> +    async function clear() {
E aqui?

2020-10-21 00:42 UTC, RaylaMedeiros commented on horarios-react/src/components/Filter/index.js
> +       <div id='filter-container'>
Tenta sempre usar aspas duplas para props

2020-10-21 00:42 UTC, RaylaMedeiros commented on horarios-react/src/components/FilterButton/index.js
> +       <button id='filter-button-container' className={active ? "active-color" : "normal-color"} onClick={() => click(content)}>
O mesmo aqui sobre as aspas

2020-10-23 00:59 UTC, RaylaMedeiros approved these changes

2020-10-23 03:45 UTC, merged