Criar disc modal
Guardians-DSC/horarios-ufcg pull request #142
Opened 2020-10-20 03:27 UTC by carolvalenca

2020-10-20 19:13 UTC, ArthurFerrao requested changes

2020-10-20 19:13 UTC, ArthurFerrao commented on horarios-react/src/components/SubjectModal/index.js
> +import cross from '../../assets/cross.svg'
Faltou adicionar esse arquivo no projeto

2020-10-20 19:13 UTC, ArthurFerrao commented on horarios-react/src/components/Table/index.js
> +                    <Subject key={elem.disciplina} subject={elem.disciplina} group={elem.turma} active={elem.active} rightClick={rightClick} leftClick={leftClick}/>
Acho que pra facilitar tu pode passar o `elem` todo para o Subject com um `subjectData={elem}`. Assim no left e right clicks vão ficar mais fáceis para pegar esses dados. Talvez até passar o showModal direto para o Subject

2020-10-20 19:13 UTC, ArthurFerrao commented on horarios-react/src/components/Table/index.js
> +        setRender(!render)
Acho que aqui tu pode usar a mesma estratégia usada no filtro para não usar esse render.

2020-10-26 21:25 UTC, ArthurFerrao requested changes

2020-10-26 21:25 UTC, ArthurFerrao commented on horarios-react/src/components/Subject/index.js
> +        <button id='subject-container' className={subjectData.active ? "active" : "normal"} onClick={() => leftClick(subjectData.disciplina, subjectData.turma)} onContextMenu={rightClick}>
Em onContextMenu tu pode chamar tua função rightClick passando o subjectData, assim vai deixar tua função rightClick mais simples.

2020-10-26 21:25 UTC, ArthurFerrao commented on horarios-react/src/components/Table/index.js
> +                showModal(subjectsArray[obj])
Quando você passar o subjectData como falei anteriormente você só vai precisar chamar o showModal passando esse dado.

2020-10-26 21:25 UTC, ArthurFerrao commented on horarios-react/src/components/Table/index.js
> +    const [subjectsArray, setSubjectsArray] = useState();
Aqui você pode colocar um array vazio no useState: 
```
const [subjectsArray, setSubjectsArray] = useState([]);
```

2020-10-26 21:25 UTC, ArthurFerrao commented on horarios-react/src/data/hours.json
> +]
Muda esse array para ter só os 4 primeiros horários

2020-10-26 21:25 UTC, ArthurFerrao commented on horarios-react/src/components/Table/index.js
> +    const [hoursArray, setHoursArray] = useState();
E aqui você pode importar novamente e usar o hours.json no useState, assim na inicialização da página a tabela não vai aparecer sem linhas.

2020-10-26 23:46 UTC, ArthurFerrao requested changes

2020-10-26 23:46 UTC, ArthurFerrao commented on horarios-react/src/components/Hour/index.js
> +            </div>
Isso daqui pode ser um map, a única coisa que muda entre as divs é o dia da semana. Poderia adicionar outro json em /data, sendo esse com esses nomes referentes aos dias da semana, e substitui essas divs por uma única div com um map.

2020-11-08 20:29 UTC, ArthurFerrao approved these changes

2020-11-08 23:50 UTC, RaylaMedeiros approved these changes

2020-11-09 07:14 UTC, merged