primeiras alteraçoes
Guardians-DSC/horarios-ufcg pull request #143
Opened 2020-11-03 01:18 UTC by carolvalenca

2020-11-07 19:12 UTC, ArthurFerrao requested changes

2020-11-07 19:12 UTC, ArthurFerrao commented on horarios-react/src/components_mobile/HourMobile/index.js
> +         let subs = await api.get(`horarios?dia=${day}&hora=${content}`)
Acho que é melhor fazer só uma requisição em TableMobile, pois sendo feita aqui ele vai sempre ficar fazendo requests pra api quando clicar para mudar de turno.

2020-11-07 19:12 UTC, ArthurFerrao commented on horarios-react/src/components_mobile/HourMobile/index.js
> +         let subs = await api.get(`horarios?dia=${day}&hora=${content}`)
No caso faz a requisição de todas as cadeiras só uma vez em TableMobile e passa pra teus outros componentes filtrando. Pois da até pra perceber que ele demora um pouco pra fazer a troca entre os turnos, e dessa forma acho que vai ficar bem mais fluido.

2020-11-07 19:12 UTC, ArthurFerrao commented on horarios-react/src/components_mobile/HourMobile/index.js
> +         let subs = await api.get(`horarios?dia=${day}&hora=${content}`)
E acho que da para aumentar a letra um pouco que ainda tem bastante espaço de tela sobrando.
![image](https://user-images.githubusercontent.com/15989443/98449644-e2513480-2113-11eb-8483-1621e0c15e89.png)

2020-11-12 14:28 UTC, RaylaMedeiros commented on horarios-react/src/components/DesktopLayout/style.css
> +@media (max-width: 485px) {
Aumenta pra 720px

2020-11-12 14:28 UTC, RaylaMedeiros commented on horarios-react/src/components/Header/style.css
> +@media (max-width: 485px) {
Aqui também

2020-11-12 14:28 UTC, RaylaMedeiros commented on horarios-react/src/components_mobile/MobileLayout/style.css
> +@media (min-width: 486px) {
E aqui pode ser 721

2020-11-14 00:08 UTC, RaylaMedeiros approved these changes

2020-11-14 15:04 UTC, ArthurFerrao approved these changes

2020-11-15 03:05 UTC, merged